services:
  mysql:
    image: mysql:5.7
    container_name: mysql-plugins
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: mysql
    ports:
      - "3309:3308"
    volumes:
      - ./docker/database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-plugins
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8089:80
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: plugins
      WORDPRESS_DB_PASSWORD: plugins
      WORDPRESS_DB_NAME: plugins
    volumes:
      - .:/var/www/html
volumes:
  wordpress:
  mysql:
